services:
  - type: web
    name: albanian-agent-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
